[build]
  command = "npm run build"
  publish = "build"
  functions = "api"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
